url: https://rohanaj.tech
baseurl: 

# Site settings
title: Rohan A J
email: rohanaj2001@gmail.com
description: "Welcome to my personal portfolio website! Here, you can find a comprehensive showcase of my work, skills, and accomplishments. As a dedicated and passionate professional, I have spent years honing my craft and developing my skills in my chosen field. Whether it's through my work experience, education, or personal projects, I strive to deliver excellence and exceed expectations in everything I do. On this website, you can browse through my projects, read about my skills and expertise, and learn more about my background and achievements. You'll find that I am a results-driven individual with a strong focus on quality, innovation, and customer satisfaction. Whether you're a potential employer, collaborator, or client, I hope this website gives you a clear picture of my capabilities and how I can add value to your organization. Thank you for visiting my personal portfolio website!"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Rohan_A_J
  - title: instagram
    url: https://www.instagram.com/aj_prototype/
  - title: linkedin
    url: https://www.linkedin.com/in/rohan-a-j-047a2319b/
  - title: github
    url: http://github.com/rohanaj2001
    

# Postal address (add as many lines as necessary)
address:
  - line: Room No. 414, NRI Hostel
  - line: MSRIT, Bangalore, 560054

# Build settings
markdown: kramdown
permalink: pretty